image_config:
  imgsz: [300, 480]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  to_rgb: true
model:
  arch: efficientnet_b0
  pretrained: false
  ckpt_path: ./weights/last.pth
  n_classes: 2
infer_config:
  mode: multiclass
  thres: null
device_id: 0
dataset:
  root: ./val
  lit_labels: ['dog', 'cat']
