- name: resize
  imgsz: 224

- name: GaussNoise
  params:
    p: 0.3

- name: OneOf
  params:
    p: 0.2
  augmentations:
    - name: OpticalDistortion

    - name: ElasticTransform

- name: OneOf
  params:
    p: 0.3
  augmentations:
    - name: MotionBlur
      params:
        p: 0.3

    - name: MedianBlur
      params:
        blur_limit: 3
        p: 0.3

    - name: Blur
      params:
        blur_limit: 3
        p: 0.3

- name: OneOf
  params:
    p: 0.4
  augmentations:
    - name: CLAHE
      params:
        clip_limit: 2

    - name: Sharpen

    - name: Emboss

    - name: RandomBrightnessContrast

- name: HueSaturationValue
  params:
    p: 0.4

- name: ShiftScaleRotate
  params:
    shift_limit: 0.025
    rotate_limit: 90
    shift_limit_x: 0.025
    shift_limit_y: 0.025
    p: 0.4

- name: ImageCompression
  params:
    quality_lower: 50

- name: Normalize
  params:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
